apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-image-deployer
  labels:
    app: kube-image-deployer
    name: kube-image-deployer
  annotations: {}
rules:
  - verbs:
      - get
      - list
      - watch
      - patch
      - update
    apiGroups:
      - apps
    resources:
      - deployments
      - statefulsets
      - daemonsets
  - verbs:
      - get
      - list
      - watch
      - patch
      - update
    apiGroups:
      - batch
    resources:
      - cronjobs
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - ''
    resources:
      - namespaces
