apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-image-deployer
  labels:
    app: kube-image-deployer
    name: kube-image-deployer
  annotations: {}
subjects:
  - kind: ServiceAccount
    name: kube-image-deployer
    namespace: kube-image-deployer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-image-deployer
