apiVersion: v1
kind: Secret
metadata:
  name: kube-image-deployer
  namespace: kube-image-deployer
  labels:
    app: kube-image-deployer
    name: kube-image-deployer
  annotations: {}
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "YourDockerRegistryUrl": {
          "username": "YourDockerRegistryUsername",
          "password": "YourDockerRegistryPassword",
        }
      }
    }
type: kubernetes.io/dockerconfigjson
