apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-image-deployer
  namespace: kube-image-deployer
  labels:
    app: kube-image-deployer
    name: kube-image-deployer
  annotations: {}
automountServiceAccountToken: true
