name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.21'
        check-latest: true

    - name: Build
      run: make

    - name: Test
      run: go test -v ./...
      env:
        TEST_DOCKER_PRIVATE_SKIP: "1"
        TEST_DOCKER_ECR_SKIP: "1"
        
    - name: Archive
      uses: actions/upload-artifact@v3
      with:
        name: kube-image-deployer
        path: build/*
